# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 678f19c5cbfafd4d1ba596611a6757e128b6da2d0bcc0e7e6e6238795bd119d14a0c473bd3809fc0f37630e30a051495a3e97777d2e5da80d3ff82e0405f8db2

test:
  secret_key_base: 0ee282aeda8e038fb94eb69c3593420d5405daaa5f78bd126ddd7c5458146cd6e2976da91ccd3cab2ee68ae411638e8b627d493379168b33966e4f966ff6d3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
